### ISSUE TITLE
Switch static asset compilation to gulp

### ISSUE THREAD

**Issue by rockwotj** [Rosebotics/RoseboticsWeb#10]

**Comment by fisherds** [comment]
+1   (seems like you should be able to +1 issues)

Can you update the Rosebotics.org developer guide with info to use the new system?  Thanks!  Here is the link: https://docs.google.com/document/d/1xylhcOuxcSn4u9VlyQkvZvE7Zw2HM3UlM7rIYTRDBNw/edit?usp=sharing

**Comment by fisherds** [comment]
yeah for Gulp. Looks great.  Pull request for clear cut isolated features are great.  For little bugs fixes just fire way with commits to master.
