### ISSUE TITLE
Link with Rose-Hulman account

### ISSUE THREAD

**Issue by rockwotj** [Rosebotics/RoseboticsWeb#13]
Instead of being able to willy-nilly enter rose username, make a "Link Rose-Hulman" button on the edit profile dialog that will prompt for credentials to check against against Rosefire. Then we will link that gmail account with those Rose-Hulman user. That way we don't get spoofing.

**Comment by fisherds** [comment]
Love it!  Not that spoofing is a real problem, but why not fix it.  You should tell that to Firebase for their email/password option. :)
