### ISSUE TITLE
Allowing a CSV import of the class roster

### ISSUE THREAD

**Issue by rockwotj** [Rosebotics/RoseboticsWeb#26]
@fisherds you only need this for class creation right? There is no need for bulk actions once the class is created correct?

**Comment by fisherds** [comment]
Short version: A single import of a CSV to create a class is all I truly need.

Long version: I usually have 2 sections of a course, so originally I was thinking it'd use bulk creation then bulk additional import.  However I could totally plan ahead and make a combined CSV for that situation.  Also "if it is doable" I usually have like 3-5 students add within the first week (often people that failed ME430 in the Fall and unexpectedly need to retake it in the Winter).  I can certainly add 3-5 manually, but if I could blindly just re-import the CSVs that would be used occasionally. 

So the priority is a single import!!! I want to be clear on that.  But fancy bells and whistles of re-import would get used in some situations.

Awesome stuff Tyler!

**Comment by rockwotj** [comment]
So if you have 2 sections, I'd allow uploading 2 different CSVs my thoughts is that it'd just bulk add both.

For now, I'm going to make you manually add the 3-5, but I can pretty easily add that in later. For know I'm just going to get the key functionality in. 

(For my reference later)
http://plnkr.co/edit/eeQbR65oE8iljm7ueGhX?p=preview

**Comment by rockwotj** [comment]
Done

**Comment by mboutell** [comment]
That will be very nice. Looking forward to using it this summer! :)
