### ISSUE TITLE
Capitalization of the email address causing no progress

### ISSUE THREAD

**Issue by fisherds** [Rosebotics/RoseboticsWeb#7]
A Google account DOES have uppercase and lowercase.  I ALWAYS convert it to lowercase before saving anything to the Datastore.  Course Builder does it differently.  They save the real case sensitive version then map it to an id.  So nobody with a capital in their email will see global progress right now.

![2015-06-16_00-11-46](https://cloud.githubusercontent.com/assets/295078/8175713/75562ee0-13bc-11e5-9029-bf6a318146ad.png)

**Comment by fisherds** [comment]
I think my fix will be two fold.
Use lowercase email in course builder
Do a data migration of all existing Student objects in all namespaces.

The first part of the fix will be done within models.py line 797.
        student = Student.get_by_email(email)
        if not student:
            # TODO(psimakov): we must move to user_id as a key
            student = Student(key_name=email)


The data migration will be a bit more work, only because it'll be our first data migration, but pretty trivially easy hopefully.  Just need to make a tmp path to do it via deferrer across all namespaces.

**Comment by rockwotj** [comment]
I agree with your above points, but I think you might want to go to a lower email in the places where I was doing login in stuff. Starting here:
https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/controllers/lessons.py#L277

Below is where the student is registered (via my auto register code), and it uses their uncapitalized name, changing this should fix the problem for the future:
https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/models/models.py#L773
But it calls this function (which you've already found):
https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/models/models.py#L784

**Comment by rockwotj** [comment]
Here
https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/controllers/utils.py#L680
and here
https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/controllers/utils.py#L638
Are also probably good spots to fix the email capitalization problem.

You could probably do a find/replace in the whole project so that every user.email() turns into user.email().lower()? I don't know if that helps

**Comment by rockwotj** [comment]
Dr. Fisher (Dave?),

I think I found why that student isn't being found. Here I'm not covering to lower. So the student is probably None.
https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/rosebotics_utils/progress_utils.py#L126

**Comment by fisherds** [comment]
Cool. Thanks for looking into it.  I plan on actually doing the fixes next
week. If you see something though you are welcome and allowed to make
commits still. You don't have to of course just know you are always welcome
to do commits if you ever want.


On Wednesday, June 24, 2015, Tyler Rockwood <notifications@github.com>
wrote:

> Dr. Fisher (Dave?),
>
> I think I found why that student isn't being found. Here I'm not covering
> to lower. So the student is probably None.
>
> https://github.com/Rosebotics/RoseboticsWeb/blob/master/appengine/rosebotics_utils/progress_utils.py#L126
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rosebotics/RoseboticsWeb/issues/7#issuecomment-115061573>
> .
>


-- 

Dr. Dave Fisher | Rose-Hulman |  fisherds@rose-hulman.com
<fisherds@rose-hulman.com> | 812-201-6488

**Comment by rockwotj** [comment]
@fisherds you fixed this correct?

**Comment by fisherds** [comment]
yeah
