### ISSUE TITLE
Autosweep options

### ISSUE THREAD

**Issue by mboutell** [Rosebotics/RoseboticsWeb#8]
Modal not always appearing when you click on the Options button for creating or editing an autosweep. BTW, you can count bug fixes, etc. for workstudy hours this term. Thanks, Tyler! :)

**Comment by rockwotj** [comment]
@mboutell Sounds good. I'll get on this when I get a chance!

**Comment by rockwotj** [comment]
@mboutell I cannot replicate this, if this happens again can you post a screenshot of the javascript console?

**Comment by fisherds** [comment]
Interesting.  Happens 100% of the time for me too.  When clicking on an Options button I get...

TypeError: Cannot read property 'tracks' of undefined
    at new <anonymous> (modal_controllers.js:275)
    at d (angular.js:3869)
    at Object.instantiate (angular.js:3880)
    at angular.js:7134
    at resolveSuccess (ui-bootstrap-tpls-0.12.1.js:2171)
    at u (angular.js:11319)
    at angular.js:11405
    at h.$eval (angular.js:12412)
    at h.$digest (angular.js:12224)
    at h.$apply (angular.js:12516)

When the modal is up and I click Export options I get....

TypeError: Cannot read property 'length' of undefined
    at new <anonymous> (app.min.js:5)
    at d (angular.min.js:34)
    at Object.instantiate (angular.min.js:34)
    at angular.min.js:66
    at new <anonymous> (app.min.js:5)
    at d (angular.min.js:34)
    at Object.instantiate (angular.min.js:34)
    at angular.min.js:66
    at resolveSuccess (ui-bootstrap-tpls-0.12.1.js:2171)
    at u (angular.min.js:97)

There must be something different about the teams we are testing with

**Comment by rockwotj** [comment]
What team is this for?

**Comment by fisherds** [comment]
I just made a new team.  I called it "Test Team".  I also tried is on my
"iOS Class Summer 2015".  The OPTIONS button (on the page) seems to always
fail, but sometimes the EXPORT OPTIONS on the popup works for creating a
new Sweep. Not sure why it sometimes works and sometimes fails yet.  BTW
I'm testing on the production version not localhost.

On Sat, Nov 28, 2015 at 12:34 AM, Tyler Rockwood <notifications@github.com>
wrote:

> What team is this for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rosebotics/RoseboticsWeb/issues/8#issuecomment-160250680>
> .
>



-- 

Dr. Dave Fisher | Rose-Hulman |  fisherds@rose-hulman.com
<fisherds@rose-hulman.com> | 812-201-6488

**Comment by rockwotj** [comment]
So I got one nailed down. `TypeError: Cannot read property 'length' of undefined` Basically I populate the available tracks and units by the progress of one student. So when you use this feature you where saying you don't use the complex picker of units, tracks and courses? Can I just blow it away then? That would fix this bugs.

**Comment by fisherds** [comment]
Yeah.  The complex unit picker was an unnecessary complication.  Ooops!  Sorry. :) Blow it away!  It'll work out better just to piggy back on what courses get displayed for this team, export all unit all the time, and have a simpler modal.  You can leave the checkboxes for:
 Include Course Progress Percentage
 Include Track Progress Percentage

They are fine and already done, but there will be no drop downs at all.  Much cleaner now. :)  I look forward to seeing what code gets deleted.


![image](https://cloud.githubusercontent.com/assets/295078/11472593/aa17951c-973b-11e5-9f30-f1c8264f10ee.png)

**Comment by rockwotj** [comment]
@mboutell now that this is closed, you'll probably have to re do all of your autosweeps. Just delete the old ones if you don't mind
